### Author: Frish2021 ###
name: deploy_7.0.0

on:
  push:
    branches: [ "master" ]
    paths:
      - "main/**/*"
      - '.github/workflows/deploy.yml'
      - 'gradle/wrapper/gradle-wrapper.properties'

permissions: write-all

jobs:
  build:
    name: Build NBT-jar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.5.0
      with: 
        java-version: '23'
        distribution: 'zulu'
        architecture: x64

    - name : Settings Environment
      run: |
        chmod +x ./scripts/set_env.sh
        sh ./scripts/set_env.sh

    - name: Chmod Script
      run: chmod +x ./gradlew

    - name: Build Package
      run: chmod +x ./scripts/build.sh && bash ./scripts/build.sh

    - name: Publish Package
      run: chmod +x ./scripts/publish.sh && bash ./scripts/publish.sh
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    - name: Upload artifacts
      uses: ncipollo/release-action@v1
      with:
        prerelease: ${{ env.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.version }}
        name: NBT ${{ env.version }}
        artifacts: |
          target/**
          LICENSE.md
